// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

/**
 * <pre>
 * This feature is part of an open beta release and is subject to the applicable
 * Beta Services Terms provided at Agreements and Terms
 * (https://www.salesforce.com/company/legal/agreements/).
 * Request to commit a Replay ID for the last processed event or for the latest
 * replay ID received in an empty batch of events.
 * </pre>
 *
 * Protobuf type {@code eventbus.v1.CommitReplayRequest}
 */
public final class CommitReplayRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eventbus.v1.CommitReplayRequest)
    CommitReplayRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommitReplayRequest.newBuilder() to construct.
  private CommitReplayRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommitReplayRequest() {
    commitRequestId_ = "";
    replayId_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommitReplayRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PubSubProto.internal_static_eventbus_v1_CommitReplayRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PubSubProto.internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CommitReplayRequest.class, Builder.class);
  }

  public static final int COMMIT_REQUEST_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object commitRequestId_ = "";
  /**
   * <pre>
   * commit_request_id to identify commit responses
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The commitRequestId.
   */
  @Override
  public String getCommitRequestId() {
    Object ref = commitRequestId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      commitRequestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * commit_request_id to identify commit responses
   * </pre>
   *
   * <code>string commit_request_id = 1;</code>
   * @return The bytes for commitRequestId.
   */
  @Override
  public com.google.protobuf.ByteString
      getCommitRequestIdBytes() {
    Object ref = commitRequestId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      commitRequestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPLAY_ID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * replayId to commit
   * </pre>
   *
   * <code>bytes replay_id = 2;</code>
   * @return The replayId.
   */
  @Override
  public com.google.protobuf.ByteString getReplayId() {
    return replayId_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitRequestId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commitRequestId_);
    }
    if (!replayId_.isEmpty()) {
      output.writeBytes(2, replayId_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitRequestId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commitRequestId_);
    }
    if (!replayId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, replayId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CommitReplayRequest)) {
      return super.equals(obj);
    }
    CommitReplayRequest other = (CommitReplayRequest) obj;

    if (!getCommitRequestId()
        .equals(other.getCommitRequestId())) return false;
    if (!getReplayId()
        .equals(other.getReplayId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMIT_REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommitRequestId().hashCode();
    hash = (37 * hash) + REPLAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReplayId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CommitReplayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommitReplayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommitReplayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommitReplayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommitReplayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommitReplayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommitReplayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommitReplayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommitReplayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CommitReplayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommitReplayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommitReplayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CommitReplayRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This feature is part of an open beta release and is subject to the applicable
   * Beta Services Terms provided at Agreements and Terms
   * (https://www.salesforce.com/company/legal/agreements/).
   * Request to commit a Replay ID for the last processed event or for the latest
   * replay ID received in an empty batch of events.
   * </pre>
   *
   * Protobuf type {@code eventbus.v1.CommitReplayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eventbus.v1.CommitReplayRequest)
          CommitReplayRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PubSubProto.internal_static_eventbus_v1_CommitReplayRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PubSubProto.internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommitReplayRequest.class, Builder.class);
    }

    // Construct using com.salesforce.eventbus.protobuf.CommitReplayRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commitRequestId_ = "";
      replayId_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PubSubProto.internal_static_eventbus_v1_CommitReplayRequest_descriptor;
    }

    @Override
    public CommitReplayRequest getDefaultInstanceForType() {
      return CommitReplayRequest.getDefaultInstance();
    }

    @Override
    public CommitReplayRequest build() {
      CommitReplayRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CommitReplayRequest buildPartial() {
      CommitReplayRequest result = new CommitReplayRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CommitReplayRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commitRequestId_ = commitRequestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.replayId_ = replayId_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CommitReplayRequest) {
        return mergeFrom((CommitReplayRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CommitReplayRequest other) {
      if (other == CommitReplayRequest.getDefaultInstance()) return this;
      if (!other.getCommitRequestId().isEmpty()) {
        commitRequestId_ = other.commitRequestId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getReplayId() != com.google.protobuf.ByteString.EMPTY) {
        setReplayId(other.getReplayId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commitRequestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              replayId_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object commitRequestId_ = "";
    /**
     * <pre>
     * commit_request_id to identify commit responses
     * </pre>
     *
     * <code>string commit_request_id = 1;</code>
     * @return The commitRequestId.
     */
    public String getCommitRequestId() {
      Object ref = commitRequestId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commitRequestId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * commit_request_id to identify commit responses
     * </pre>
     *
     * <code>string commit_request_id = 1;</code>
     * @return The bytes for commitRequestId.
     */
    public com.google.protobuf.ByteString
        getCommitRequestIdBytes() {
      Object ref = commitRequestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commitRequestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * commit_request_id to identify commit responses
     * </pre>
     *
     * <code>string commit_request_id = 1;</code>
     * @param value The commitRequestId to set.
     * @return This builder for chaining.
     */
    public Builder setCommitRequestId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      commitRequestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * commit_request_id to identify commit responses
     * </pre>
     *
     * <code>string commit_request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitRequestId() {
      commitRequestId_ = getDefaultInstance().getCommitRequestId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * commit_request_id to identify commit responses
     * </pre>
     *
     * <code>string commit_request_id = 1;</code>
     * @param value The bytes for commitRequestId to set.
     * @return This builder for chaining.
     */
    public Builder setCommitRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commitRequestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * replayId to commit
     * </pre>
     *
     * <code>bytes replay_id = 2;</code>
     * @return The replayId.
     */
    @Override
    public com.google.protobuf.ByteString getReplayId() {
      return replayId_;
    }
    /**
     * <pre>
     * replayId to commit
     * </pre>
     *
     * <code>bytes replay_id = 2;</code>
     * @param value The replayId to set.
     * @return This builder for chaining.
     */
    public Builder setReplayId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      replayId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * replayId to commit
     * </pre>
     *
     * <code>bytes replay_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplayId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      replayId_ = getDefaultInstance().getReplayId();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eventbus.v1.CommitReplayRequest)
  }

  // @@protoc_insertion_point(class_scope:eventbus.v1.CommitReplayRequest)
  private static final CommitReplayRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CommitReplayRequest();
  }

  public static CommitReplayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitReplayRequest>
      PARSER = new com.google.protobuf.AbstractParser<CommitReplayRequest>() {
    @Override
    public CommitReplayRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommitReplayRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CommitReplayRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CommitReplayRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

