// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

/**
 * <pre>
 * Event publish result that the Publish RPC method returns. The result contains replay_id or a publish error.
 * </pre>
 *
 * Protobuf type {@code eventbus.v1.PublishResult}
 */
public final class PublishResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eventbus.v1.PublishResult)
    PublishResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PublishResult.newBuilder() to construct.
  private PublishResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PublishResult() {
    replayId_ = com.google.protobuf.ByteString.EMPTY;
    correlationKey_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PublishResult();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PubSubProto.internal_static_eventbus_v1_PublishResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PublishResult.class, Builder.class);
  }

  public static final int REPLAY_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Replay ID of the event
   * </pre>
   *
   * <code>bytes replay_id = 1;</code>
   * @return The replayId.
   */
  @Override
  public com.google.protobuf.ByteString getReplayId() {
    return replayId_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private Error error_;
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   * @return The error.
   */
  @Override
  public Error getError() {
    return error_ == null ? Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   * Publish error if any
   * </pre>
   *
   * <code>.eventbus.v1.Error error = 2;</code>
   */
  @Override
  public ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? Error.getDefaultInstance() : error_;
  }

  public static final int CORRELATION_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object correlationKey_ = "";
  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The correlationKey.
   */
  @Override
  public String getCorrelationKey() {
    Object ref = correlationKey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      correlationKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Correlation key of the ProducerEvent
   * </pre>
   *
   * <code>string correlation_key = 3;</code>
   * @return The bytes for correlationKey.
   */
  @Override
  public com.google.protobuf.ByteString
      getCorrelationKeyBytes() {
    Object ref = correlationKey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      correlationKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!replayId_.isEmpty()) {
      output.writeBytes(1, replayId_);
    }
    if (error_ != null) {
      output.writeMessage(2, getError());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, correlationKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!replayId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, replayId_);
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(correlationKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, correlationKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PublishResult)) {
      return super.equals(obj);
    }
    PublishResult other = (PublishResult) obj;

    if (!getReplayId()
        .equals(other.getReplayId())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getCorrelationKey()
        .equals(other.getCorrelationKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReplayId().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (37 * hash) + CORRELATION_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getCorrelationKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PublishResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublishResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublishResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublishResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublishResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PublishResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PublishResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PublishResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublishResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PublishResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PublishResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PublishResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PublishResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Event publish result that the Publish RPC method returns. The result contains replay_id or a publish error.
   * </pre>
   *
   * Protobuf type {@code eventbus.v1.PublishResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eventbus.v1.PublishResult)
          PublishResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PubSubProto.internal_static_eventbus_v1_PublishResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublishResult.class, Builder.class);
    }

    // Construct using com.salesforce.eventbus.protobuf.PublishResult.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      replayId_ = com.google.protobuf.ByteString.EMPTY;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      correlationKey_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PubSubProto.internal_static_eventbus_v1_PublishResult_descriptor;
    }

    @Override
    public PublishResult getDefaultInstanceForType() {
      return PublishResult.getDefaultInstance();
    }

    @Override
    public PublishResult build() {
      PublishResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PublishResult buildPartial() {
      PublishResult result = new PublishResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PublishResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.replayId_ = replayId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.correlationKey_ = correlationKey_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PublishResult) {
        return mergeFrom((PublishResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PublishResult other) {
      if (other == PublishResult.getDefaultInstance()) return this;
      if (other.getReplayId() != com.google.protobuf.ByteString.EMPTY) {
        setReplayId(other.getReplayId());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (!other.getCorrelationKey().isEmpty()) {
        correlationKey_ = other.correlationKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              replayId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              correlationKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString replayId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @return The replayId.
     */
    @Override
    public com.google.protobuf.ByteString getReplayId() {
      return replayId_;
    }
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @param value The replayId to set.
     * @return This builder for chaining.
     */
    public Builder setReplayId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      replayId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Replay ID of the event
     * </pre>
     *
     * <code>bytes replay_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplayId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      replayId_ = getDefaultInstance().getReplayId();
      onChanged();
      return this;
    }

    private Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
            Error, Error.Builder, ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     * @return The error.
     */
    public Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder setError(Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder setError(
        Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder mergeError(Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          error_ != null &&
          error_ != Error.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    public ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     * Publish error if any
     * </pre>
     *
     * <code>.eventbus.v1.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Error, Error.Builder, ErrorOrBuilder>
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Error, Error.Builder, ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private Object correlationKey_ = "";
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return The correlationKey.
     */
    public String getCorrelationKey() {
      Object ref = correlationKey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        correlationKey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return The bytes for correlationKey.
     */
    public com.google.protobuf.ByteString
        getCorrelationKeyBytes() {
      Object ref = correlationKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        correlationKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @param value The correlationKey to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationKey(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      correlationKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrelationKey() {
      correlationKey_ = getDefaultInstance().getCorrelationKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation key of the ProducerEvent
     * </pre>
     *
     * <code>string correlation_key = 3;</code>
     * @param value The bytes for correlationKey to set.
     * @return This builder for chaining.
     */
    public Builder setCorrelationKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      correlationKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eventbus.v1.PublishResult)
  }

  // @@protoc_insertion_point(class_scope:eventbus.v1.PublishResult)
  private static final PublishResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PublishResult();
  }

  public static PublishResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishResult>
      PARSER = new com.google.protobuf.AbstractParser<PublishResult>() {
    @Override
    public PublishResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublishResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PublishResult> getParserForType() {
    return PARSER;
  }

  @Override
  public PublishResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

