// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

public interface PublishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.PublishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Topic to publish on
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The topicName.
   */
  String getTopicName();
  /**
   * <pre>
   * Topic to publish on
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The bytes for topicName.
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  java.util.List<ProducerEvent>
      getEventsList();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  ProducerEvent getEvents(int index);
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  java.util.List<? extends ProducerEventOrBuilder>
      getEventsOrBuilderList();
  /**
   * <pre>
   * Batch of ProducerEvent(s) to send
   * </pre>
   *
   * <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
   */
  ProducerEventOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <pre>
   * For internal Salesforce use only.
   * </pre>
   *
   * <code>string auth_refresh = 3;</code>
   * @return The authRefresh.
   */
  String getAuthRefresh();
  /**
   * <pre>
   * For internal Salesforce use only.
   * </pre>
   *
   * <code>string auth_refresh = 3;</code>
   * @return The bytes for authRefresh.
   */
  com.google.protobuf.ByteString
      getAuthRefreshBytes();
}
