// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

public final class PubSubProto {
  private PubSubProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_TopicInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_TopicInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_TopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_TopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_EventHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_EventHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ProducerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_ProducerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ConsumerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_ConsumerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_PublishResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_SchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_SchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_SchemaInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_SchemaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_PublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_PublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ManagedFetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_ManagedFetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_ManagedFetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_ManagedFetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_CommitReplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventbus_v1_CommitReplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventbus_v1_CommitReplayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031pubsub_api-original.proto\022\013eventbus.v1" +
      "\"\203\001\n\tTopicInfo\022\022\n\ntopic_name\030\001 \001(\t\022\023\n\013te" +
      "nant_guid\030\002 \001(\t\022\023\n\013can_publish\030\003 \001(\010\022\025\n\r" +
      "can_subscribe\030\004 \001(\010\022\021\n\tschema_id\030\005 \001(\t\022\016" +
      "\n\006rpc_id\030\006 \001(\t\"\"\n\014TopicRequest\022\022\n\ntopic_" +
      "name\030\001 \001(\t\")\n\013EventHeader\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\014\"j\n\rProducerEvent\022\n\n\002id\030\001 \001" +
      "(\t\022\021\n\tschema_id\030\002 \001(\t\022\017\n\007payload\030\003 \001(\014\022)" +
      "\n\007headers\030\004 \003(\0132\030.eventbus.v1.EventHeade" +
      "r\"M\n\rConsumerEvent\022)\n\005event\030\001 \001(\0132\032.even" +
      "tbus.v1.ProducerEvent\022\021\n\treplay_id\030\002 \001(\014" +
      "\"^\n\rPublishResult\022\021\n\treplay_id\030\001 \001(\014\022!\n\005" +
      "error\030\002 \001(\0132\022.eventbus.v1.Error\022\027\n\017corre" +
      "lation_key\030\003 \001(\t\":\n\005Error\022$\n\004code\030\001 \001(\0162" +
      "\026.eventbus.v1.ErrorCode\022\013\n\003msg\030\002 \001(\t\"\224\001\n" +
      "\014FetchRequest\022\022\n\ntopic_name\030\001 \001(\t\0220\n\rrep" +
      "lay_preset\030\002 \001(\0162\031.eventbus.v1.ReplayPre" +
      "set\022\021\n\treplay_id\030\003 \001(\014\022\025\n\rnum_requested\030" +
      "\004 \001(\005\022\024\n\014auth_refresh\030\005 \001(\t\"\204\001\n\rFetchRes" +
      "ponse\022*\n\006events\030\001 \003(\0132\032.eventbus.v1.Cons" +
      "umerEvent\022\030\n\020latest_replay_id\030\002 \001(\014\022\016\n\006r" +
      "pc_id\030\003 \001(\t\022\035\n\025pending_num_requested\030\004 \001" +
      "(\005\"\"\n\rSchemaRequest\022\021\n\tschema_id\030\001 \001(\t\"D" +
      "\n\nSchemaInfo\022\023\n\013schema_json\030\001 \001(\t\022\021\n\tsch" +
      "ema_id\030\002 \001(\t\022\016\n\006rpc_id\030\003 \001(\t\"f\n\016PublishR" +
      "equest\022\022\n\ntopic_name\030\001 \001(\t\022*\n\006events\030\002 \003" +
      "(\0132\032.eventbus.v1.ProducerEvent\022\024\n\014auth_r" +
      "efresh\030\003 \001(\t\"a\n\017PublishResponse\022+\n\007resul" +
      "ts\030\001 \003(\0132\032.eventbus.v1.PublishResult\022\021\n\t" +
      "schema_id\030\002 \001(\t\022\016\n\006rpc_id\030\003 \001(\t\"\267\001\n\023Mana" +
      "gedFetchRequest\022\027\n\017subscription_id\030\001 \001(\t" +
      "\022\026\n\016developer_name\030\002 \001(\t\022\025\n\rnum_requeste" +
      "d\030\003 \001(\005\022\024\n\014auth_refresh\030\004 \001(\t\022B\n\030commit_" +
      "replay_id_request\030\005 \001(\0132 .eventbus.v1.Co" +
      "mmitReplayRequest\"\307\001\n\024ManagedFetchRespon" +
      "se\022*\n\006events\030\001 \003(\0132\032.eventbus.v1.Consume" +
      "rEvent\022\030\n\020latest_replay_id\030\002 \001(\014\022\016\n\006rpc_" +
      "id\030\003 \001(\t\022\035\n\025pending_num_requested\030\004 \001(\005\022" +
      ":\n\017commit_response\030\005 \001(\0132!.eventbus.v1.C" +
      "ommitReplayResponse\"C\n\023CommitReplayReque" +
      "st\022\031\n\021commit_request_id\030\001 \001(\t\022\021\n\treplay_" +
      "id\030\002 \001(\014\"}\n\024CommitReplayResponse\022\031\n\021comm" +
      "it_request_id\030\001 \001(\t\022\021\n\treplay_id\030\002 \001(\014\022!" +
      "\n\005error\030\003 \001(\0132\022.eventbus.v1.Error\022\024\n\014pro" +
      "cess_time\030\004 \001(\003*1\n\tErrorCode\022\013\n\007UNKNOWN\020" +
      "\000\022\013\n\007PUBLISH\020\001\022\n\n\006COMMIT\020\002*4\n\014ReplayPres" +
      "et\022\n\n\006LATEST\020\000\022\014\n\010EARLIEST\020\001\022\n\n\006CUSTOM\020\002" +
      "2\347\002\n\006PubSub\022F\n\tSubscribe\022\031.eventbus.v1.F" +
      "etchRequest\032\032.eventbus.v1.FetchResponse(" +
      "\0010\001\022@\n\tGetSchema\022\032.eventbus.v1.SchemaReq" +
      "uest\032\027.eventbus.v1.SchemaInfo\022=\n\010GetTopi" +
      "c\022\031.eventbus.v1.TopicRequest\032\026.eventbus." +
      "v1.TopicInfo\022D\n\007Publish\022\033.eventbus.v1.Pu" +
      "blishRequest\032\034.eventbus.v1.PublishRespon" +
      "se\022N\n\rPublishStream\022\033.eventbus.v1.Publis" +
      "hRequest\032\034.eventbus.v1.PublishResponse(\001" +
      "0\001Ba\n com.salesforce.eventbus.protobufB\013" +
      "PubSubProtoP\001Z.github.com/developerforce" +
      "/pub-sub-api/go/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_eventbus_v1_TopicInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventbus_v1_TopicInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_TopicInfo_descriptor,
        new String[] { "TopicName", "TenantGuid", "CanPublish", "CanSubscribe", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_TopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eventbus_v1_TopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_TopicRequest_descriptor,
        new String[] { "TopicName", });
    internal_static_eventbus_v1_EventHeader_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eventbus_v1_EventHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_EventHeader_descriptor,
        new String[] { "Key", "Value", });
    internal_static_eventbus_v1_ProducerEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_eventbus_v1_ProducerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_ProducerEvent_descriptor,
        new String[] { "Id", "SchemaId", "Payload", "Headers", });
    internal_static_eventbus_v1_ConsumerEvent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_eventbus_v1_ConsumerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_ConsumerEvent_descriptor,
        new String[] { "Event", "ReplayId", });
    internal_static_eventbus_v1_PublishResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_eventbus_v1_PublishResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_PublishResult_descriptor,
        new String[] { "ReplayId", "Error", "CorrelationKey", });
    internal_static_eventbus_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_eventbus_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_Error_descriptor,
        new String[] { "Code", "Msg", });
    internal_static_eventbus_v1_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_eventbus_v1_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_FetchRequest_descriptor,
        new String[] { "TopicName", "ReplayPreset", "ReplayId", "NumRequested", "AuthRefresh", });
    internal_static_eventbus_v1_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_eventbus_v1_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_FetchResponse_descriptor,
        new String[] { "Events", "LatestReplayId", "RpcId", "PendingNumRequested", });
    internal_static_eventbus_v1_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_eventbus_v1_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_SchemaRequest_descriptor,
        new String[] { "SchemaId", });
    internal_static_eventbus_v1_SchemaInfo_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_eventbus_v1_SchemaInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_SchemaInfo_descriptor,
        new String[] { "SchemaJson", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_eventbus_v1_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_PublishRequest_descriptor,
        new String[] { "TopicName", "Events", "AuthRefresh", });
    internal_static_eventbus_v1_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_eventbus_v1_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_PublishResponse_descriptor,
        new String[] { "Results", "SchemaId", "RpcId", });
    internal_static_eventbus_v1_ManagedFetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_eventbus_v1_ManagedFetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_ManagedFetchRequest_descriptor,
        new String[] { "SubscriptionId", "DeveloperName", "NumRequested", "AuthRefresh", "CommitReplayIdRequest", });
    internal_static_eventbus_v1_ManagedFetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_eventbus_v1_ManagedFetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_ManagedFetchResponse_descriptor,
        new String[] { "Events", "LatestReplayId", "RpcId", "PendingNumRequested", "CommitResponse", });
    internal_static_eventbus_v1_CommitReplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_eventbus_v1_CommitReplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_CommitReplayRequest_descriptor,
        new String[] { "CommitRequestId", "ReplayId", });
    internal_static_eventbus_v1_CommitReplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_eventbus_v1_CommitReplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventbus_v1_CommitReplayResponse_descriptor,
        new String[] { "CommitRequestId", "ReplayId", "Error", "ProcessTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
