// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

public interface SchemaInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.SchemaInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Avro schema in JSON format
   * </pre>
   *
   * <code>string schema_json = 1;</code>
   * @return The schemaJson.
   */
  String getSchemaJson();
  /**
   * <pre>
   * Avro schema in JSON format
   * </pre>
   *
   * <code>string schema_json = 1;</code>
   * @return The bytes for schemaJson.
   */
  com.google.protobuf.ByteString
      getSchemaJsonBytes();

  /**
   * <pre>
   * Schema fingerprint
   * </pre>
   *
   * <code>string schema_id = 2;</code>
   * @return The schemaId.
   */
  String getSchemaId();
  /**
   * <pre>
   * Schema fingerprint
   * </pre>
   *
   * <code>string schema_id = 2;</code>
   * @return The bytes for schemaId.
   */
  com.google.protobuf.ByteString
      getSchemaIdBytes();

  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 3;</code>
   * @return The rpcId.
   */
  String getRpcId();
  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 3;</code>
   * @return The bytes for rpcId.
   */
  com.google.protobuf.ByteString
      getRpcIdBytes();
}
