// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

public interface TopicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventbus.v1.TopicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the topic to retrieve.
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The topicName.
   */
  String getTopicName();
  /**
   * <pre>
   * The name of the topic to retrieve.
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The bytes for topicName.
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();
}
