// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub_api-original.proto

package org.wso2.carbon.inbound.sf.pubsub.com.salesforce.eventbus.protobuf;

/**
 * <pre>
 * Contains information about a topic and uniquely identifies it. TopicInfo is returned by the GetTopic RPC method.
 * </pre>
 *
 * Protobuf type {@code eventbus.v1.TopicInfo}
 */
public final class TopicInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eventbus.v1.TopicInfo)
    TopicInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TopicInfo.newBuilder() to construct.
  private TopicInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopicInfo() {
    topicName_ = "";
    tenantGuid_ = "";
    schemaId_ = "";
    rpcId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TopicInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PubSubProto.internal_static_eventbus_v1_TopicInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PubSubProto.internal_static_eventbus_v1_TopicInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TopicInfo.class, Builder.class);
  }

  public static final int TOPIC_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object topicName_ = "";
  /**
   * <pre>
   * Topic name
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The topicName.
   */
  @Override
  public String getTopicName() {
    Object ref = topicName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      topicName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Topic name
   * </pre>
   *
   * <code>string topic_name = 1;</code>
   * @return The bytes for topicName.
   */
  @Override
  public com.google.protobuf.ByteString
      getTopicNameBytes() {
    Object ref = topicName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      topicName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_GUID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object tenantGuid_ = "";
  /**
   * <pre>
   * Tenant/org GUID
   * </pre>
   *
   * <code>string tenant_guid = 2;</code>
   * @return The tenantGuid.
   */
  @Override
  public String getTenantGuid() {
    Object ref = tenantGuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tenantGuid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tenant/org GUID
   * </pre>
   *
   * <code>string tenant_guid = 2;</code>
   * @return The bytes for tenantGuid.
   */
  @Override
  public com.google.protobuf.ByteString
      getTenantGuidBytes() {
    Object ref = tenantGuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tenantGuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAN_PUBLISH_FIELD_NUMBER = 3;
  private boolean canPublish_ = false;
  /**
   * <pre>
   * Is publishing allowed?
   * </pre>
   *
   * <code>bool can_publish = 3;</code>
   * @return The canPublish.
   */
  @Override
  public boolean getCanPublish() {
    return canPublish_;
  }

  public static final int CAN_SUBSCRIBE_FIELD_NUMBER = 4;
  private boolean canSubscribe_ = false;
  /**
   * <pre>
   * Is subscription allowed?
   * </pre>
   *
   * <code>bool can_subscribe = 4;</code>
   * @return The canSubscribe.
   */
  @Override
  public boolean getCanSubscribe() {
    return canSubscribe_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object schemaId_ = "";
  /**
   * <pre>
   * ID of the current topic schema, which can be used for
   * publishing of generically serialized events.
   * </pre>
   *
   * <code>string schema_id = 5;</code>
   * @return The schemaId.
   */
  @Override
  public String getSchemaId() {
    Object ref = schemaId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      schemaId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the current topic schema, which can be used for
   * publishing of generically serialized events.
   * </pre>
   *
   * <code>string schema_id = 5;</code>
   * @return The bytes for schemaId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSchemaIdBytes() {
    Object ref = schemaId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      schemaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RPC_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object rpcId_ = "";
  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 6;</code>
   * @return The rpcId.
   */
  @Override
  public String getRpcId() {
    Object ref = rpcId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      rpcId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * RPC ID used to trace errors.
   * </pre>
   *
   * <code>string rpc_id = 6;</code>
   * @return The bytes for rpcId.
   */
  @Override
  public com.google.protobuf.ByteString
      getRpcIdBytes() {
    Object ref = rpcId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      rpcId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topicName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantGuid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantGuid_);
    }
    if (canPublish_ != false) {
      output.writeBool(3, canPublish_);
    }
    if (canSubscribe_ != false) {
      output.writeBool(4, canSubscribe_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, schemaId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, rpcId_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topicName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantGuid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantGuid_);
    }
    if (canPublish_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, canPublish_);
    }
    if (canSubscribe_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, canSubscribe_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, schemaId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, rpcId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TopicInfo)) {
      return super.equals(obj);
    }
    TopicInfo other = (TopicInfo) obj;

    if (!getTopicName()
        .equals(other.getTopicName())) return false;
    if (!getTenantGuid()
        .equals(other.getTenantGuid())) return false;
    if (getCanPublish()
        != other.getCanPublish()) return false;
    if (getCanSubscribe()
        != other.getCanSubscribe()) return false;
    if (!getSchemaId()
        .equals(other.getSchemaId())) return false;
    if (!getRpcId()
        .equals(other.getRpcId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTopicName().hashCode();
    hash = (37 * hash) + TENANT_GUID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantGuid().hashCode();
    hash = (37 * hash) + CAN_PUBLISH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanPublish());
    hash = (37 * hash) + CAN_SUBSCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanSubscribe());
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaId().hashCode();
    hash = (37 * hash) + RPC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRpcId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TopicInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopicInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopicInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopicInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopicInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopicInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopicInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopicInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopicInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TopicInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopicInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopicInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TopicInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Contains information about a topic and uniquely identifies it. TopicInfo is returned by the GetTopic RPC method.
   * </pre>
   *
   * Protobuf type {@code eventbus.v1.TopicInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eventbus.v1.TopicInfo)
          TopicInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PubSubProto.internal_static_eventbus_v1_TopicInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PubSubProto.internal_static_eventbus_v1_TopicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopicInfo.class, Builder.class);
    }

    // Construct using com.salesforce.eventbus.protobuf.TopicInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topicName_ = "";
      tenantGuid_ = "";
      canPublish_ = false;
      canSubscribe_ = false;
      schemaId_ = "";
      rpcId_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PubSubProto.internal_static_eventbus_v1_TopicInfo_descriptor;
    }

    @Override
    public TopicInfo getDefaultInstanceForType() {
      return TopicInfo.getDefaultInstance();
    }

    @Override
    public TopicInfo build() {
      TopicInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TopicInfo buildPartial() {
      TopicInfo result = new TopicInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(TopicInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topicName_ = topicName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantGuid_ = tenantGuid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.canPublish_ = canPublish_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.canSubscribe_ = canSubscribe_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.schemaId_ = schemaId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.rpcId_ = rpcId_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TopicInfo) {
        return mergeFrom((TopicInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TopicInfo other) {
      if (other == TopicInfo.getDefaultInstance()) return this;
      if (!other.getTopicName().isEmpty()) {
        topicName_ = other.topicName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantGuid().isEmpty()) {
        tenantGuid_ = other.tenantGuid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCanPublish() != false) {
        setCanPublish(other.getCanPublish());
      }
      if (other.getCanSubscribe() != false) {
        setCanSubscribe(other.getCanSubscribe());
      }
      if (!other.getSchemaId().isEmpty()) {
        schemaId_ = other.schemaId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getRpcId().isEmpty()) {
        rpcId_ = other.rpcId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              topicName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantGuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              canPublish_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              canSubscribe_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              schemaId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              rpcId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object topicName_ = "";
    /**
     * <pre>
     * Topic name
     * </pre>
     *
     * <code>string topic_name = 1;</code>
     * @return The topicName.
     */
    public String getTopicName() {
      Object ref = topicName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Topic name
     * </pre>
     *
     * <code>string topic_name = 1;</code>
     * @return The bytes for topicName.
     */
    public com.google.protobuf.ByteString
        getTopicNameBytes() {
      Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Topic name
     * </pre>
     *
     * <code>string topic_name = 1;</code>
     * @param value The topicName to set.
     * @return This builder for chaining.
     */
    public Builder setTopicName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      topicName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Topic name
     * </pre>
     *
     * <code>string topic_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicName() {
      topicName_ = getDefaultInstance().getTopicName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Topic name
     * </pre>
     *
     * <code>string topic_name = 1;</code>
     * @param value The bytes for topicName to set.
     * @return This builder for chaining.
     */
    public Builder setTopicNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      topicName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object tenantGuid_ = "";
    /**
     * <pre>
     * Tenant/org GUID
     * </pre>
     *
     * <code>string tenant_guid = 2;</code>
     * @return The tenantGuid.
     */
    public String getTenantGuid() {
      Object ref = tenantGuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tenantGuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Tenant/org GUID
     * </pre>
     *
     * <code>string tenant_guid = 2;</code>
     * @return The bytes for tenantGuid.
     */
    public com.google.protobuf.ByteString
        getTenantGuidBytes() {
      Object ref = tenantGuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tenantGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tenant/org GUID
     * </pre>
     *
     * <code>string tenant_guid = 2;</code>
     * @param value The tenantGuid to set.
     * @return This builder for chaining.
     */
    public Builder setTenantGuid(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantGuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant/org GUID
     * </pre>
     *
     * <code>string tenant_guid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantGuid() {
      tenantGuid_ = getDefaultInstance().getTenantGuid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant/org GUID
     * </pre>
     *
     * <code>string tenant_guid = 2;</code>
     * @param value The bytes for tenantGuid to set.
     * @return This builder for chaining.
     */
    public Builder setTenantGuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantGuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean canPublish_ ;
    /**
     * <pre>
     * Is publishing allowed?
     * </pre>
     *
     * <code>bool can_publish = 3;</code>
     * @return The canPublish.
     */
    @Override
    public boolean getCanPublish() {
      return canPublish_;
    }
    /**
     * <pre>
     * Is publishing allowed?
     * </pre>
     *
     * <code>bool can_publish = 3;</code>
     * @param value The canPublish to set.
     * @return This builder for chaining.
     */
    public Builder setCanPublish(boolean value) {
      
      canPublish_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Is publishing allowed?
     * </pre>
     *
     * <code>bool can_publish = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanPublish() {
      bitField0_ = (bitField0_ & ~0x00000004);
      canPublish_ = false;
      onChanged();
      return this;
    }

    private boolean canSubscribe_ ;
    /**
     * <pre>
     * Is subscription allowed?
     * </pre>
     *
     * <code>bool can_subscribe = 4;</code>
     * @return The canSubscribe.
     */
    @Override
    public boolean getCanSubscribe() {
      return canSubscribe_;
    }
    /**
     * <pre>
     * Is subscription allowed?
     * </pre>
     *
     * <code>bool can_subscribe = 4;</code>
     * @param value The canSubscribe to set.
     * @return This builder for chaining.
     */
    public Builder setCanSubscribe(boolean value) {
      
      canSubscribe_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Is subscription allowed?
     * </pre>
     *
     * <code>bool can_subscribe = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanSubscribe() {
      bitField0_ = (bitField0_ & ~0x00000008);
      canSubscribe_ = false;
      onChanged();
      return this;
    }

    private Object schemaId_ = "";
    /**
     * <pre>
     * ID of the current topic schema, which can be used for
     * publishing of generically serialized events.
     * </pre>
     *
     * <code>string schema_id = 5;</code>
     * @return The schemaId.
     */
    public String getSchemaId() {
      Object ref = schemaId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        schemaId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * ID of the current topic schema, which can be used for
     * publishing of generically serialized events.
     * </pre>
     *
     * <code>string schema_id = 5;</code>
     * @return The bytes for schemaId.
     */
    public com.google.protobuf.ByteString
        getSchemaIdBytes() {
      Object ref = schemaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        schemaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the current topic schema, which can be used for
     * publishing of generically serialized events.
     * </pre>
     *
     * <code>string schema_id = 5;</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      schemaId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the current topic schema, which can be used for
     * publishing of generically serialized events.
     * </pre>
     *
     * <code>string schema_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      schemaId_ = getDefaultInstance().getSchemaId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the current topic schema, which can be used for
     * publishing of generically serialized events.
     * </pre>
     *
     * <code>string schema_id = 5;</code>
     * @param value The bytes for schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      schemaId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object rpcId_ = "";
    /**
     * <pre>
     * RPC ID used to trace errors.
     * </pre>
     *
     * <code>string rpc_id = 6;</code>
     * @return The rpcId.
     */
    public String getRpcId() {
      Object ref = rpcId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rpcId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * RPC ID used to trace errors.
     * </pre>
     *
     * <code>string rpc_id = 6;</code>
     * @return The bytes for rpcId.
     */
    public com.google.protobuf.ByteString
        getRpcIdBytes() {
      Object ref = rpcId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rpcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * RPC ID used to trace errors.
     * </pre>
     *
     * <code>string rpc_id = 6;</code>
     * @param value The rpcId to set.
     * @return This builder for chaining.
     */
    public Builder setRpcId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      rpcId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RPC ID used to trace errors.
     * </pre>
     *
     * <code>string rpc_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRpcId() {
      rpcId_ = getDefaultInstance().getRpcId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RPC ID used to trace errors.
     * </pre>
     *
     * <code>string rpc_id = 6;</code>
     * @param value The bytes for rpcId to set.
     * @return This builder for chaining.
     */
    public Builder setRpcIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rpcId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eventbus.v1.TopicInfo)
  }

  // @@protoc_insertion_point(class_scope:eventbus.v1.TopicInfo)
  private static final TopicInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TopicInfo();
  }

  public static TopicInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopicInfo>
      PARSER = new com.google.protobuf.AbstractParser<TopicInfo>() {
    @Override
    public TopicInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TopicInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TopicInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public TopicInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

